export {default as LandingPage} from './LandingPage/LandingPage'
export {default as Dashboard}  from './Dashboard/Dashboard';
export {default as Profile} from './Profile/Profile'
export {default as NotFound} from './NotFoundPage/NotFound'
export {default as Orders} from './Orders/Orders'
export {default as AssignedAgents} from './DeliveryAgents/AssignedAgents';
export {default as AgentDetails}  from './AgentDetails/AgentDetails';
export {default as Management}  from './Dashboard/Management';
export {default as OrderDetails} from './OrderDetails/OrderDetails';
export {default as Agents} from './DeliveryAgents/Agent'
