export  {default as DeliveryImg} from './images/deliverySvg.webp';
export {default as LogoImg} from './images/logo.png';
export {default as HidePasswordIcon} from './svgs/EyeClose.svg';
export {default as ShowPasswordIcon} from './svgs/EyeOpen.svg';
export {default as DeliveryIcon} from './svgs/delivery-icon.png'
export {default as DashboardIcon} from './svgs/dashmenu.svg'
export {default as NotificationIcon} from './svgs/Notification.svg'
export {default as DetailsIcon} from './svgs/DetailsIcon.svg'
export {default as DashboardImg} from './svgs/Dashboard.svg'
export {default as LeftArrowIcon} from './svgs/leftArrow.svg'
export {default as Item1} from './svgs/item1.svg'
export {default as Item2} from './svgs/item2.svg'
export {default as FilterIcon} from './svgs/filter-icon.svg'
export {default as AddIcon} from './svgs/add-icon (1).svg'
export {default as DeleteIcon} from './svgs/delete.svg'
export {default as BusyIcon} from './svgs/busy-icon.svg'
export {default as EditIcon} from './svgs/EditIcon.svg'
export {default as CheckTick} from './svgs/CheckGroup.svg'
export {default as StatusTick} from './svgs/cancel-icon.svg'
export {default as TimeTick} from './svgs/time.svg'
export {default as RejectedIcon} from './svgs/Rejected.svg'
export {default as DeliveryUserIcon} from './svgs/delivery-user.svg'