export {default as AddIcon} from './svgs/addIcon.svg';
export {default as CheckedRadioIcon} from './svgs/selected-radio.svg';
export {default as RadioIcon} from './svgs/inselected.svg';
export {default as DeliveryImg} from './svgs/landing-img.svg';
export {default as LogoImg} from './svgs/logo.jpg';
export {default as LogoDark} from './svgs/logodark.svg';
export {default as HidePasswordIcon} from './svgs/EyeClose.svg';
export {default as ShowPasswordIcon} from './svgs/EyeOpen.svg';
export {default as CalenderIcon} from './svgs/cal-icon.svg';
export {default as SearchIcon} from './svgs/search-icon.svg';
export {default as LeftArrowIcon} from './svgs/arrow-right.svg'
export {default as LeftArrowIconHeader} from './svgs/back-arrow.svg'
export {default as NotificationIcon} from './svgs/bell.svg'
export {default as ChatIcon} from './svgs/chat-icon.svg'
export {default as EditIcon} from './svgs/editicon.svg';
export {default as EmailIcon} from './svgs/email.svg';
export {default as CompanyIcon} from './svgs/company.svg';
export {default as CheckIcon} from './svgs/checkIcon.svg';
export {default as MenuIcon} from './svgs/menu.svg';
export {default as LocationIcon} from './svgs/location.svg';
export {default as DeliveryTruckIcon} from './svgs/delivery-truck.svg'
export {default as SimpleLineIcon} from './svgs/simple-line.svg'
export {default as VericalMenuIcon} from './svgs/charm_menu-kebab.svg'
export {default as CashIcon} from './svgs/ph_money-duotone.svg'
export {default as UploadIcon} from './svgs/foundation_upload-cloud.svg'
export {default as CrossIcon} from './svgs/basil_cross-outline.svg'
export {default as CameraIcon} from './svgs/camera-icon.svg'
export {default as GalleryIcon} from './svgs/gallery-icon.svg'
export {default as SuccessIcon} from './svgs/success.svg'
export {default as DetailEditIcon} from './svgs/basil_edit-outline.svg'
export {default as ArrowIcon} from './svgs/arrow.svg'
export {default as MicrophoneIcon} from './svgs/micro-phone.svg'
export {default as PhoneIcon} from './svgs/material-symbols_call-sharp.svg'
export {default as SendIcon} from './svgs/bi_send-fill.svg'
export {default as CallSharpIcon} from './svgs/call-sharp-green.svg'
export {default as CheckTimeIcon} from './svgs/material-symbols_check.svg'
export {default as QrCodeIcon} from './svgs/qr.svg'
export {default as DangerIcon} from './svgs/danger.svg'
export {default as InputEmailIcon} from './svgs/mail.svg'
export {default as InputEyeOffIcon} from './svgs/eye-off.svg'
export {default as InputEyeOnIcon} from './svgs/EyeOpen.svg'
export {default as StarIcon} from './svgs/star.svg';
export {default as StarWhiteIcon} from './svgs/whitestar.svg';
export {default as PickupImg} from './svgs/pickup.svg';
export {default as DeliverImg} from './svgs/deliver.svg';
export {default as NotAvailableIcon} from './svgs/notAvailable.svg';