export {default as DeliveryImg} from './svgs/landing-img.svg';
export {default as LogoImg} from './svgs/logo.jpg';
export {default as HidePasswordIcon} from './svgs/EyeClose.svg';
export {default as ShowPasswordIcon} from './svgs/EyeOpen.svg';
export {default as UploadIcon} from './svgs/Upload.svg';
export {default as CalenderIcon} from './svgs/calender.svg';
export {default as SearchIcon} from './svgs/search-icon.svg';
export {default as LeftArrowIcon} from './images/arrowLeft.svg'
export {default as NotificationIcon} from './svgs/bell.svg'
export {default as ChatIcon} from './svgs/chat-icon.svg'
export {default as EditIcon} from './svgs/editicon.svg';
export {default as EmailIcon} from './svgs/emailIcon.svg';
export {default as CompanyIcon} from './svgs/company.svg';
export {default as CheckIcon} from './svgs/checkIcon.svg';
export {default as MenuIcon} from './svgs/menu.svg';
export {default as LocationIcon} from './svgs/location.svg';
export {default as DeliveryTruckIcon} from './svgs/delivery-truck.svg'
export {default as SimpleLineIcon} from './svgs/simple-line.svg'
export {default as VericalMenuIcon} from './svgs/charm_menu-kebab.svg'
export {default as CashIcon} from './svgs/ph_money-duotone.svg'