name: Build and deploy Node.js app to Azure Web App - DeliveryManagement

on:
  push:
    branches:
      - dev-mobile
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install npm dependencies
        run: |
          cd AgentMobileApp && npm install
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Install npm dependencies
        run: |
         cd AgentMobileApp && npm install
      - name: Build Android Release
        run: |
          cd AgentMobileApp/android && chmod +x ./gradlew && ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: AgentMobileApp/android/app/build/outputs/apk/release/
